apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - payment-api-rollout.yaml
  - analysistemplate-success-rate.yaml
  - payment-api-service.yaml
  - payment-api-servicemonitor.yaml
  - slo/recording-rules.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: nucleus
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false
